<a href="https://colab.research.google.com/github/krishn12323/aiml_lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
# activity 1: create array
import numpy as np

a=np.array([10,20,30,40])
print(a)

b=np.arange(1,11)
print(b)

c=np.linspace(0,1,5)
print(c)


[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [31]:
# A2: matrix operation

A=np.array([[1,2],
           [3,4]])
B=np.array([[5,4],
           [7,8]])

print(A+B)
print(A*B)
print(A-B)
print(A@B)



[[ 6  6]
 [10 12]]
[[ 5  8]
 [21 32]]
[[-4 -2]
 [-4 -4]]
[[19 20]
 [43 44]]


In [32]:
#A3:Statistics
marks= np.array([70,65,80,90,88])

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

78.6
90
65
9.789790600416334


In [33]:
#A4
#weather datra of july month
import numpy as np

# Days of July
days = np.arange(1, 32)

# Average temperature (°C) of each day
temp = np.array([
    30.5, 31.0, 31.2, 30.8, 31.5,
    32.0, 31.7, 30.9, 31.3, 32.2,
    33.0, 32.8, 31.9, 32.4, 33.5,
    34.0, 34.5, 35.2, 34.8, 35.5,
    36.0, 35.8, 34.6, 33.9, 32.7,
    31.8, 31.2, 30.7, 30.3, 29.8,
    29.5
])

print(np.max(temp))
print(np.argmax(temp)+1)

print(np.min(temp))
print(np.argmin(temp)+1)


print(np.mean(temp))
print(temp>35)
print(temp[temp>35])

36.0
21
29.5
31
32.483870967741936
[False False False False False False False False False False False False
 False False False False False  True False  True  True  True False False
 False False False False False False False]
[35.2 35.5 36.  35.8]
